# Generated by Django 2.2.1 on 2019-06-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190618_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
