# Generated by Django 2.2.1 on 2019-06-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20190622_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='userRating',
            field=models.FloatField(default=0.0),
        ),
    ]
